### ISSUE TITLE
Tiny feedback

### ISSUE THREAD

**Issue by luciusmagn** [Alannek1992/rust-academy#1]
https://github.com/Alannek1992/rust-academy/blob/235e4172e0a43ac85196dd07406fd796b0cbe289/transmuter/src/error.rs#L3

Unless you are writing a no_std library, I would refer to `std` and not `core` here.

If you are curious, on nightly Rust (and hopefully it will come to stable soon), one can hack together a
`to_camel_case()` with iterators:

```rust
#![feature(iter_map_windows)]

fn to_camel_case2(input: &str) -> String {
    " ".chars()
        .chain(input.chars())
        .map_windows(|[a, b]| {
            if !a.is_alphanumeric() {
                b.to_ascii_uppercase()
            } else {
                *b
            }
        })
        .filter(|c| c.is_alphanumeric())
        .collect()
}
```

There are ways to do this on stable too, but they would be cumbersome and/or essentially rewrites of what you have.

Also I love your test strings :D

**Comment by Alannek1992** [comment]
Ah, that Result type was rather typo than intention. Thanks for pointing that out.. you really go through everything, dont you? :P

Interesting.. I ll definitely have a look at nightly Rust to check that out. Also some other interesting stuff is definitely going on there.

Closed by: d43922d544b9d9e81dd334f4c268a695c989cde0
